### PR TITLE
Init Django Project

### LINKED ISSUE #5: Issue #0 Init Django Project
Initialize the Django framework within the repository

### PR DESCRIPTION
**Pull request by j-neeley**
Initialization of Django Project

### CODE REVIEW

**Review by Ragnarok9401 — APPROVED** [review]
This is epic

**Review by AlonsoArreguin — APPROVED** [review]
Looks like a good start to me!

**Review by SyddWhit — APPROVED** [review]
Great start!

**Review by colbystuart — APPROVED** [review]
looks pretty swag

**Pull request merged**
